version: "3.8"
services:
    mysql-db:
        image: mysql:8.0
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: secret
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - emp-net
    php-web:
        build:
            context: .
        container_name: php-web
        volumes:
            - .:/var/www/html
        ports:
            - "8080:80"
        depends_on:
            - mysql-db
        networks:
            - emp-net
volumes:
    mysql_data:
networks:
    emp-net:
